name: frenzygram
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.4
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  firebase_storage: ^11.2.5
  emoji_picker_flutter: ^1.6.1
  firebase_messaging: ^14.6.5
  http: ^0.13.5
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.3.2
  shared_preferences: ^2.2.0
  
flutter_native_splash:
  color: "#ffffff"
  image: images/unicorn.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.0"
  flutter_native_splash: "^2.3.1"
  flutter_lints: ^2.0.2
  

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/unicorn.png"
  min_sdk_android: 21 
  
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  assets:
    - images/
 
