// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCThkO0fWaWK9yW6GvlsZWY_sGHuwyH2Jw',
    appId: '1:693407250899:android:f757e4f9c510138b585726',
    messagingSenderId: '693407250899',
    projectId: 'frenzygram-fa689',
    storageBucket: 'frenzygram-fa689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP925YIjPXa22RIjMWCo5x2CTGbn7606U',
    appId: '1:693407250899:ios:aa67a9a5f292899d585726',
    messagingSenderId: '693407250899',
    projectId: 'frenzygram-fa689',
    storageBucket: 'frenzygram-fa689.appspot.com',
    androidClientId: '693407250899-169t35hpi0ngjo1stoujfifcs06nsc6f.apps.googleusercontent.com',
    iosClientId: '693407250899-dm0ru2q6sj0qbcrn5d7d702u8m95pfaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.frenzygram',
  );
}
